---
title:               Snarky Remarks
tagline:             It can't be helped.
login:               foxnewsnetwork
password:            asdf123
name:                Thomas Chen
twitter:             thomashanchen
github:              foxnewsnetwork
email:               foxnewsnetwork@gmail.com
google_analytics_id: YOUR_GA_ID